//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.5420
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Izdanie.WebCabinet.Medo.DTO
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedoDocumentDTO", Namespace="http://schemas.datacontract.org/2004/07/Izdanie.WebCabinet.Medo.DTO")]
    public partial class MedoDocumentDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EoNumberField;
        
        private System.Guid IdField;
        
        private System.Nullable<System.DateTime> PublishDateField;
        
        private Izdanie.Domain.Enums.InspectorCheckStatus StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EoNumber
        {
            get
            {
                return this.EoNumberField;
            }
            set
            {
                this.EoNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PublishDate
        {
            get
            {
                return this.PublishDateField;
            }
            set
            {
                this.PublishDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Izdanie.Domain.Enums.InspectorCheckStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IzdanieSyncData", Namespace="http://schemas.datacontract.org/2004/07/Izdanie.WebCabinet.Medo.DTO")]
    public partial class IzdanieSyncData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Izdanie.WebCabinet.Medo.DTO.DocumentTypeDTO[] DocumentTypeListField;
        
        private Izdanie.WebCabinet.Medo.DTO.DocumentTypeSignatoryAuthorityDTO[] DocumentTypeSignatoryAuthorityListField;
        
        private Izdanie.WebCabinet.Medo.DTO.MedoDocumentTypeDTO[] MedoDocumentTypeListField;
        
        private Izdanie.WebCabinet.Medo.DTO.MedoSignatoryAuthorityDTO[] MedoSignatoryAuthorityListField;
        
        private Izdanie.WebCabinet.Medo.DTO.SignatoryAuthorityDTO[] SignatoryAuthorityListField;
        
        private System.DateTime SyncDateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Izdanie.WebCabinet.Medo.DTO.DocumentTypeDTO[] DocumentTypeList
        {
            get
            {
                return this.DocumentTypeListField;
            }
            set
            {
                this.DocumentTypeListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Izdanie.WebCabinet.Medo.DTO.DocumentTypeSignatoryAuthorityDTO[] DocumentTypeSignatoryAuthorityList
        {
            get
            {
                return this.DocumentTypeSignatoryAuthorityListField;
            }
            set
            {
                this.DocumentTypeSignatoryAuthorityListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Izdanie.WebCabinet.Medo.DTO.MedoDocumentTypeDTO[] MedoDocumentTypeList
        {
            get
            {
                return this.MedoDocumentTypeListField;
            }
            set
            {
                this.MedoDocumentTypeListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Izdanie.WebCabinet.Medo.DTO.MedoSignatoryAuthorityDTO[] MedoSignatoryAuthorityList
        {
            get
            {
                return this.MedoSignatoryAuthorityListField;
            }
            set
            {
                this.MedoSignatoryAuthorityListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Izdanie.WebCabinet.Medo.DTO.SignatoryAuthorityDTO[] SignatoryAuthorityList
        {
            get
            {
                return this.SignatoryAuthorityListField;
            }
            set
            {
                this.SignatoryAuthorityListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SyncDate
        {
            get
            {
                return this.SyncDateField;
            }
            set
            {
                this.SyncDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentTypeDTO", Namespace="http://schemas.datacontract.org/2004/07/Izdanie.WebCabinet.Medo.DTO")]
    public partial class DocumentTypeDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool HasMedoField;
        
        private System.Guid IdField;
        
        private bool IsActiveField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasMedo
        {
            get
            {
                return this.HasMedoField;
            }
            set
            {
                this.HasMedoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentTypeSignatoryAuthorityDTO", Namespace="http://schemas.datacontract.org/2004/07/Izdanie.WebCabinet.Medo.DTO")]
    public partial class DocumentTypeSignatoryAuthorityDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid DocumentTypeIdField;
        
        private bool HasMedoField;
        
        private System.Guid IdField;
        
        private bool IsActiveField;
        
        private System.Guid SignatoryAuthorityIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DocumentTypeId
        {
            get
            {
                return this.DocumentTypeIdField;
            }
            set
            {
                this.DocumentTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasMedo
        {
            get
            {
                return this.HasMedoField;
            }
            set
            {
                this.HasMedoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SignatoryAuthorityId
        {
            get
            {
                return this.SignatoryAuthorityIdField;
            }
            set
            {
                this.SignatoryAuthorityIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedoDocumentTypeDTO", Namespace="http://schemas.datacontract.org/2004/07/Izdanie.WebCabinet.Medo.DTO")]
    public partial class MedoDocumentTypeDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid DocumentTypeIdField;
        
        private System.Guid IdField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DocumentTypeId
        {
            get
            {
                return this.DocumentTypeIdField;
            }
            set
            {
                this.DocumentTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedoSignatoryAuthorityDTO", Namespace="http://schemas.datacontract.org/2004/07/Izdanie.WebCabinet.Medo.DTO")]
    public partial class MedoSignatoryAuthorityDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        private string NameField;
        
        private System.Guid SignatoryAuthorityIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SignatoryAuthorityId
        {
            get
            {
                return this.SignatoryAuthorityIdField;
            }
            set
            {
                this.SignatoryAuthorityIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignatoryAuthorityDTO", Namespace="http://schemas.datacontract.org/2004/07/Izdanie.WebCabinet.Medo.DTO")]
    public partial class SignatoryAuthorityDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool HasMedoField;
        
        private System.Guid IdField;
        
        private bool IsActiveField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasMedo
        {
            get
            {
                return this.HasMedoField;
            }
            set
            {
                this.HasMedoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
}
namespace Izdanie.Domain.Enums
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InspectorCheckStatus", Namespace="http://schemas.datacontract.org/2004/07/Izdanie.Domain.Enums")]
    public enum InspectorCheckStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoValue = -100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved_LoadedToPublic_DirectToPublic = -7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved_LoadedToPublic_Postponed = -6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InWorkGroup = -2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApprovedGroup = -3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RejectedGroup = -4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RevocatedGroup = -5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Draft_Uploaded = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InWork_Uploaded = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InWork_CheckedByInspector_NoErrors = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InWork_CheckedByInspector_ErrorsInCard = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected_CheckedByInspector_ErrorsInDocument = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved_CheckedByMainInspector = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected_CheckedByMainInspector = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Revocated_CheckedByMainInspector = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved_TransmittedToClosedSegment = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InWork_LoadedToClosedSegment = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected_CheckedByClosedSegmentInspector_ErrorsInDocument = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InWork_CheckedByClosedSegmentInspector_NoErrors = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InWork_CheckedByClosedSegmentInspector_ErrorsInCard = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved_CheckedByClosedSegmentMainInspector = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected_CheckedByClosedSegmentMainInspector = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Revocated_CheckedByClosedSegmentMainInspector = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved_TransmittedToEtalon = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved_LoadedToClosedSegment = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved_LoadedToEtalon = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved_TransmittedToPublic = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved_LoadedToPublic = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Revocated_ByPublicAdmin = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Published = 42,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMedoIntegrationService")]
public interface IMedoIntegrationService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedoIntegrationService/ProcessDocument", ReplyAction="http://tempuri.org/IMedoIntegrationService/ProcessDocumentResponse")]
    void ProcessDocument(string path, string userName, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedoIntegrationService/SetDocumentAsSended", ReplyAction="http://tempuri.org/IMedoIntegrationService/SetDocumentAsSendedResponse")]
    void SetDocumentAsSended(System.Guid id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedoIntegrationService/GetFinishedDocuments", ReplyAction="http://tempuri.org/IMedoIntegrationService/GetFinishedDocumentsResponse")]
    Izdanie.WebCabinet.Medo.DTO.MedoDocumentDTO[] GetFinishedDocuments();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedoIntegrationService/SynchronizeDictionaries", ReplyAction="http://tempuri.org/IMedoIntegrationService/SynchronizeDictionariesResponse")]
    Izdanie.WebCabinet.Medo.DTO.IzdanieSyncData SynchronizeDictionaries(System.DateTime lastSyncDate);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IMedoIntegrationServiceChannel : IMedoIntegrationService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class MedoIntegrationServiceClient : System.ServiceModel.ClientBase<IMedoIntegrationService>, IMedoIntegrationService
{
    
    public MedoIntegrationServiceClient()
    {
    }
    
    public MedoIntegrationServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MedoIntegrationServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MedoIntegrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MedoIntegrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void ProcessDocument(string path, string userName, string password)
    {
        base.Channel.ProcessDocument(path, userName, password);
    }
    
    public void SetDocumentAsSended(System.Guid id)
    {
        base.Channel.SetDocumentAsSended(id);
    }
    
    public Izdanie.WebCabinet.Medo.DTO.MedoDocumentDTO[] GetFinishedDocuments()
    {
        return base.Channel.GetFinishedDocuments();
    }
    
    public Izdanie.WebCabinet.Medo.DTO.IzdanieSyncData SynchronizeDictionaries(System.DateTime lastSyncDate)
    {
        return base.Channel.SynchronizeDictionaries(lastSyncDate);
    }
}
